export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS';
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANY_BY_ID_SUCCESS = 'FETCH_COMPANY_BY_ID_SUCCESS';

export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENT_BY_ID_SUCCESS = 'FETCH_CLIENT_BY_ID_SUCCESS';
export const UPDATE_CLIENT_BY_ID_SUCCESS = 'UPDATE_CLIENT_BY_ID_SUCCESS';
export const DELETE_CLIENT_BY_ID_SUCCESS = 'DELETE_CLIENT_BY_ID_SUCCESS';

export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';